# Generated by ./update.sh - do not update manually!
# Last updated: 2026-10-10
{ fetchurl }:
let
  any-darwin = {
    version = "";
    src = fetchurl {
      url = "";
      hash = "";
    };
  };
in
{
  aarch64-darwin = any-darwin;
  aarch64-linux = {
    version = "3.2.34-53644";
    src = fetchurl {
      url = "https://qqdl.gtimg.cn/qqfile/QQNT/9.9.36/beta/9ee04bef/linuxqq_3.2.34-53644_arm64.deb";
      hash = "sha256-GBuJXLVzVI45blS7BUjMqS/9wbGksBj6RVG7BiOF/co=";
    };
  };
  x86_64-linux = {
    version = "3.2.34-53644";
    src = fetchurl {
      url = "https://qqdl.gtimg.cn/qqfile/QQNT/9.9.36/beta/9ee04bef/linuxqq_3.2.34-53644_amd64.deb";
      hash = "sha256-Q2xl4d0oQi4SiiHL3bX+Ti5sB51/J/7CVB4BTTjMM24=";
    };
  };
}
