name: build and push docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写发布Releases的版本号（留空不发布）'
        required: true

env:
  TAG: "${{ github.event.inputs.tag }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v20
    - uses: DeterminateSystems/flakehub-cache-action@main
    - name: build
      run: nix build .
    - name: Load Docker Image
      run: |
        nix build .#dockerImage
        docker load < result
    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker Image
      run: |
        docker tag llonebot:latest initialencounter/llonebot:latest
        docker tag llonebot:latest initialencounter/llonebot:${{ env.TAG }}
        docker push initialencounter/llonebot:latest
        docker push initialencounter/llonebot:${{ env.TAG }}
